language: python
python:
- '3.0'
- '3.1'
- '3.2'
- '3.4'
- '3.5'
- '3.6'
sudo: false
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -y update
- sudo apt-get -y install build-essential
- sudo apt-get -y install g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
- g++ --version
install:
- pip install --process-dependency-links .
script:
- python setup.py test
deploy:
  provider: pypi
  on:
    tags: true
  user: bung87
  password:
    secure: gWuhEaZTPR7Ffbu4AnG6Hfm7NwqZrfWO9jD9y7m8Pm07TuTBb9+S5OJOw4Yt1/MU/jxVJ6x/G38efEYfJq4xMyuhj8qG5mFvFFvO6HOwnujdkNEv0hft4gv/9G8m6DfUKOxl1JKYcJFfSF2ClMIaLeMIaNb0lpi9/zJJ0OYibsGJDN+W7SMKJZyo7GptwMpyZttT6NxlhLrrOxbSxsSyQqXvJ7rdzvBn4T/qtsldFrryVGw3oVJuLciBrjnRg+T6Y3WChted76KTsfXAj9Z2M9wIA06I6NzZ0QtLuE/mj0Smq2TNzFP/OZns4Yhws+KQrRRB30YyRqwGFQNGJ+AkS6YwPbaYhCHZWbzyydyw7ScecR0KPc4QhmOKrWtMpZJgCNQjBfSwyndjjg7o7WI1PLoYTZKtOohcH29Jgd/Shd6XIeHc1yVYC/vNTaegcvNjueXU2Is6nDUdS462qJqNef7gZQlSXpKQHT8sOMRTDC7Z9qS4X+RpN5uEATThFX1WpMkaSm5Th3+mnGD5IdJUyqfxZSYfHYloK+3bRVqMT5xN8X1HRPccngk957h1CqXHQBwpzTb93slcGZa5wu7269fYtlYlnqEtJ8gno1v1YDMMh0c/bb72IH6xzKxIIwP7cYxGkdEiPeGcLe0jigPYxsji/zNue1FfBXRTfcBdUkI=
