language: python
python:
- '3.4'
- '3.5'
- '3.6'
sudo: false
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -y update
- sudo apt-get -y install build-essential
- sudo apt-get -y install g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
- g++ --version
install:
- pip install .
script:
- python setup.py test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: 15huSEOAx77kToKx4gjKKsnuyNTFnraMV4VoUiZOsLy7HTt2Xr99rQpKdoFUDrQ+X/1FVWuQ23f/v4XB6wHjDSjw6sgiEU+tcW3kRDQRFBiXuWxbIr/b8+MXWXz6ltO2tPuTIxD5+V5jLefwcM1OcfhTev/S8Uk0fscr5yPe87s8PSfASbmYLsyLj02oG5aFTrudZ4OEEUbWJsyxJ0AZZ3fZ0+vWvfLqPWNU/ylSDngw4SFxX9xPRHxT8DqyWvL+G1rAJzl3GKPiVk0XLv3YimwUG3V/m8hktEWCR2NbL8gPX7wak+B/wvxN2f3K6bqGVWZVtGwzo6L0RPrJJMM8RVeg59fufaygDcSFHMAB/uIX8bIkZcLoHitwpi5RHqy9jK7OfMTswkCJvRIow2XDhf+GZApl5WI33dpY6NZXlsyW0DVT5Zta8vLLcZDGPPRKQonWX2TJGF3xm5RWSeSmtkbNvbRkVH22ffipi3DfcSNZtN8c/2XTVdR9ES5rX72SP7V0Zp5o/qAQP2vLe2oYAAWdEoDPM+5BS6FbTeeXyOkLkziED3N7x+Z0kjcu/ltsgQiScwKfryJRzXhRPeHAw2ad7zbEuxzQxFzrJf+AubRlfVQuniVTncmWeLNAQdUJIBPJOli8UvnFOb4uveMEPwM2smF4jYR1jAM5NlPzEDc=
  skip_existing: true